---
title: "[<i class='fas fa-download'></i>](static/files/JCR_Resume/JCR_Resume.pdf) Resume"
output:
  html_document: 
    toc: true
    toc_float: true
---

# Education

* PhD in Computer Science:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
["Análisis e integración de información de datos biológicos mediante análisis funcional"](https://jcrodriguez1989.github.io/tesis_doctoral/)

<!-- Research topic: "Statistical/computational methodologies for functional  -->
<!-- analysis at the level of gene isomorphisms". -->

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[FAMAF](http://www.famaf.unc.edu.ar/) - [National University of Córdoba](https://www.unc.edu.ar/english/) *(2014 - 2019)*

* MSc in Applied Statistics

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[FCA](http://www.agro.unc.edu.ar/), [FCE](http://www.eco.unc.edu.ar/) and [FAMAF](http://www.famaf.unc.edu.ar/) - [National University of Córdoba](https://www.unc.edu.ar/english/) *(2014 - )*

* MSc in Computer Science

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[FAMAF](http://www.famaf.unc.edu.ar/) - [National University of Córdoba](https://www.unc.edu.ar/english/) *(2007 - 2012)*

* BSc in Computer Science

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[FAMAF](http://www.famaf.unc.edu.ar/) - [National University of Córdoba](https://www.unc.edu.ar/english/) *(2007 - 2009)*


# Teaching Activities

* Teaching Assistant

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[FAMAF](http://www.famaf.unc.edu.ar/) - [National University of Córdoba](https://www.unc.edu.ar/english/) *(May 2014 - March 2021)*

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
Algorithms and Data Structures

<!-- **Postgraduate course** -->

<!-- [IBYME - CONICET](https://www.ibyme.org.ar/) *(December 2015)* -->

<!-- "Chromatin and gene regulation: from the gen to the genome" -->

* Teaching Associate

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
Faculty of Engineering - [Catholic University of Córdoba](https://ucc.edu.ar/) *(2013 - 2014)*

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
Programming in Python

* Student Assistant

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[FAMAF](http://www.famaf.unc.edu.ar/) - [National University of Córdoba](https://www.unc.edu.ar/english/) *(2011 - 2012)*

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
Algorithms and Data Structures II & Databases


# Industry Experience

* Data Science Advisor

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[Good Tree](https://www.getgoodtree.com/) **_(October 2020 - Present)_**

* Lead Data Scientist

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[Winclap](https://www.winclap.com/) *(February 2020 - November 2020)*

* Software Engineer

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[Applied Research (INVAP](http://www.invap.com.ar/en/); *June 2013 - October 2013)*

* QA Engineer

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
HPC Group at [Intel Corporation](https://www.intel.com) *(June 2012 - June 2013)*


# R Packages

**CRAN**

* [rco](https://cran.r-project.org/package=rco): The R Code Optimizer.

* [autokeras](https://cran.r-project.org/package=autokeras): R Interface to ['AutoKeras'](https://autokeras.com/).

* [rflights](https://cran.r-project.org/package=rflights): Query Plane Tickets using the '[Kiwi](https://www.kiwi.com)' API.

**Bioconductor**

* [MIGSA](http://bioconductor.org/packages/MIGSA/): Massive and Integrative Gene Set Analysis.

**GitHub**

* [shinyParallel](https://github.com/jcrodriguez1989/shinyParallel): Run Shiny Applications in a Multi-Session Mode.

* [shinyWYSIWYG](https://github.com/jcrodriguez1989/shinyWYSIWYG): Shiny What You See Is What You Get (WYSIWYG) editor.

* [interactingan](https://github.com/jcrodriguez1989/interactingan): Interactive Presentation Ninja.

* [heyshiny](https://github.com/jcrodriguez1989/heyshiny): New `shiny` input that translates audio to text.

# Awards and Distinctions

* University Award

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
Diploma with Special Mention

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[National University of Córdoba](https://www.unc.edu.ar/english/) to the second best average of 
2011 graduates

* Substitute for First Escort

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[FAMAF](http://www.famaf.unc.edu.ar/) - [National University of Córdoba](https://www.unc.edu.ar/english/) *(2011)*

# Mentoring

* [2020 Google Summer of Code mentor w/R-project](https://summerofcode.withgoogle.com/projects/#6187591176552448/)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
Mentoring of student Rahul Saxena to work on [the `rco` R package](https://jcrodriguez1989.github.io/rco/).

* 2019 Google Code-in mentor w/R-project

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
Mentored pre-university students with [short tasks](https://codein.withgoogle.com/archive/2019/organization/5963835628847104/task/) related to [the `rco` R package](https://jcrodriguez1989.github.io/rco/).

# Scholarships

* 2019 Google Summer of Code student w/R-project

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
Was awarded a [GSoC project](https://summerofcode.withgoogle.com/archive/2019/projects/6300906386096128/) to develop [the R Code Optimizer, `rco`](https://jcrodriguez1989.github.io/rco/), R package.

* [Fulbright](https://www.cies.org/) exchange visiting scholarship

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
At the [University of Florida](http://www.ufl.edu/) *(2018)*

* Doctoral Scholarship

<!-- Research topic: "Information analysis and integration methodologies for genomic  -->
<!-- data from mass sequencing technologies." -->

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[National Scientific and Technical Research Council, Argentina (CONICET](https://www.conicet.gov.ar/?lan=en); *2013 - 2019*)

* Master's Scholarship

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
Government of Córdoba, Argentina *(2007 - 2011)*


# Publications

**2019**

* Rodriguez, J. C., Luraschi J.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[Auto-Keras: An R easily accessible deep learning library](https://github.com/LatinR/presentaciones-LatinR2019#auto-keras-an-r-easily-accessible-deep-learning-library).

<!-- At the Latinamerican Conference About the Use of R in R&D. Santiago, Chile. -->

* Rodriguez, J. C., Merino, G. A., Llera A. S., Fernández, E. A.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[Massive integrative gene set analysis enables functional characterization of ](https://doi.org/10.1016/j.jbi.2019.103157)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[breast cancer subtypes.](https://doi.org/10.1016/j.jbi.2019.103157) **(Journal)**

**2018**

* Rodriguez, J. C., Vargas Rojas C., Fernández, E. A.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[ShinyWYSIWYG: a Shiny What You See Is What You Get editor](https://github.com/LatinR/presentaciones-LatinR2018#shinywysiwyg-a-shiny-what-you-see-is-what-you-get-editor-pdf-presentaci%C3%B3n--shiny-app--repositorio).

<!-- At the Latinamerican Conference About the Use of R in R&D. Buenos Aires. -->

**2017**

* Rodriguez, J. C., Prato L., Llera A. S., Fernández, E. A.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
Effects of RNA-Seq data gene analysis methods, on the 
over-representation analysis of gene 

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
sets.

<!-- At the Argentine Congress of Bioengineering. Córdoba. -->

**2016**

* Rodriguez, J. C., González, G. A., Fresno, C., Llera, A. S., Fernández, E. A.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[Improving Information Retrieval in Functional Analysis.](https://doi.org/10.1016/j.compbiomed.2016.09.017) **(Journal)**

<!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Computers in Biology and Medicine. Amsterdam; Year: 2016 vol. 79 p. 10 - 20 *(Journal)*. -->

* Rodriguez, J. C., Merino, G. A., Prato L., Llera A. S., Fernández, E. A.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[The impact of RNA-Seq differential expression algorithms on ](https://www.researchgate.net/publication/311946206_The_impact_of_RNA-Seq_differential_expression_algorithms_on_Over_-Representation_Analysis_of_Gene_Sets)
[Over-Representation Analysis](https://www.researchgate.net/publication/311946206_The_impact_of_RNA-Seq_differential_expression_algorithms_on_Over_-Representation_Analysis_of_Gene_Sets)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[of Gene Sets](https://www.researchgate.net/publication/311946206_The_impact_of_RNA-Seq_differential_expression_algorithms_on_Over_-Representation_Analysis_of_Gene_Sets).

<!-- In International Society for Computational Biology Latin America Bioinformatics  -->
<!-- Conference. Buenos Aires. -->

**2015**

* Rodriguez, J. C., González, G., Fresno, C., & Fernández, E. A.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[Integrative Functional Analysis Improves Information Retrieval in Breast Cancer](https://doi.org/10.1007/978-3-319-25751-8_6).

<!-- In Iberoamerican Congress on Pattern Recognition (pp. 43-50). Springer International -->
<!-- Publishing. -->

* Fresno C., González G. A., Merino G. A., Rodriguez J. C., Balzarini M., Fernández E. A.

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[DNA Microarrays Quality Control by ANOVA-PCA / PLS decomposition](https://fcf.unse.edu.ar/eventos/gab2014/contenido/pdf/DE01.pdf).

<!-- In XIX Scientific Meeting of the Biometry Argentine Group. -->


# Research Exchange

* At the [Ana Conesa Lab](http://conesalab.org/).

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[University of Florida](http://www.ufl.edu/), USA *(October 2018 - December 2018)*

* At the [Genomics of Gene Expression](http://conesalab.org/) group.

<!-- Developing a European American NGS analysis Network. -->

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
[Centro de Investigación Prícipe Felipe](www.cipf.es/en/), Valencia, Spain *(October 2017 - December 2017)*

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
DEANN project (Marie Curie IRSES, European Commission, 2013)

<!-- Languages: -->

<!-- Spanish: Native. -->
<!-- English: Advanced. -->
