---
title: "<br/><br/>Talks"
output:
  html_document: 
    toc: false
    toc_float: true
---

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

**November 2023** "Artificial intelligence for the cannabis industry." [ES]

Presenting a retrospective on the application of data science in the cannabis industry, covering key challenges, emerging opportunities, and key developments from my years of experience.

`r emo::ji("earth")` [ExpoCannabis](https://expocannabis.com.ar/) - `r emo::ji("newspaper")` [Flyer](https://x.com/expocannabisarg/status/1706707316546871560)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

**May 2023** "Turning our monolithic Shiny app into a microservices-based structure." [EN]

A 25-minute talk that presents the journey of refactoring large complex Shiny applications into a more manageable and scalable system based on microservices.

`r emo::ji("earth")` [ShinyConf](https://www.shinyconf.com/) - `r emo::ji("movie")` [Video](https://www.youtube.com/watch?v=pzKkdadIgFU)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

**October 2020** "Contributing to open source in R." [ES]

A 15-minute talk that presents how to contribute to open source projects in R. From finding an open-source project to submitting your first pull request.

`r emo::ji("earth")` [ReproHack 2020](https://latin-r.com/blog/reprohack) - `r emo::ji("movie")` [Video](https://www.youtube.com/watch?v=TVsfF3yJLlw) - `r emo::ji("folder")` [Materials](https://github.com/jcrodriguez1989/firstContributionsInR/)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

**October 2020** "Interactive web applications with Shiny." [ES]

A two-hour tutorial introducing how to develop interactive web applications from R using the `{shiny}` package.

`r emo::ji("earth")` [LatinR Conference 2020](https://latin-r.com/cronograma/#session-2) - `r emo::ji("movie")` [Video](https://www.youtube.com/watch?v=sryZCC9z2po) - `r emo::ji("folder")` [Materials](https://etherpad.wikimedia.org/p/latinr_taller_shiny)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

**April 2019** "R in the high performance computing center: Intro to MPI and massive arrays." [ES]

A two-hour talk introducing how to work with MPI in R (`{Rmpi}`) and handling huge data arrays (`{ff}`), followed by some hands-on examples.

`r emo::ji("earth")` [National University of Córdoba](https://www.unc.edu.ar/english/) - `r emo::ji("folder")` [Slides](https://www.dropbox.com/s/eo94ooukb63hhyg/02_CAD_en_R.html?dl=1) - `r emo::ji("folder")` [Sample Code & Source Code](https://www.dropbox.com/sh/jkrlarrxkx84wu2/AAA5OQT8v8PGcuv0N42xEXgka?dl=1)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

**March 2019** "R in the high performance computing center: Parallelizing." [ES]

A two-hour talk presenting how to parallelize R code (`{parallel}`), translating `for` loops into `lapply`, passing parameters from bash to my R script and run it in a SLURM cluster.

`r emo::ji("earth")` [National University of Córdoba](https://www.unc.edu.ar/english/) - `r emo::ji("folder")` [Slides](https://www.dropbox.com/s/hr03b5v74xi2f3v/01_paralelizando.html?dl=1) - `r emo::ji("folder")` [Sample Code & Source Code](https://www.dropbox.com/sh/nvp8bd6qz6057n6/AAAFh0u5XxULCYzZW4XQYVbGa?dl=1)

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

**May 2017** "Optimizing your R code!" [ES]

A two-hour talk presenting tools and tips that allow to evaluate and make the most of the execution time of R code:
profiling, benchmarking, `compiler`, pre-allocating memory, vectorization, standard and internal functions, `apply` vs `for` (scopes and translation), parallelism (`{BiocParallel}`).

`r emo::ji("earth")` [Catholic University of Córdoba](https://ucc.edu.ar/) - `r emo::ji("folder")` [Slides](https://www.dropbox.com/s/umgh1bmgbk2q87s/Seminario_speedup_R.pdf?dl=1) - `r emo::ji("folder")` [Sample Code](https://www.dropbox.com/sh/3lt5o3hi45uevhv/AADYWIC6oUgbY2EQAjPNBulZa?dl=1)
